language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 2.7
          env: TOXENV=py27-pyramid15
        - python: 3.5
          env: TOXENV=py27-cover,py35-cover,coverage
        - python: 3.5
          env: TOXENV=lint
        - python: 3.5
          env: TOXENV=docs

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"

