language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy
          env: TOXENV=pypy
        - python: 3.5
          env: TOXENV=py2-cover,py3-cover,coverage
        - python: 3.5
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=py27-pyramid12
        - python: 2.7
          env: TOXENV=py27-pyramid13
        - python: 2.7
          env: TOXENV=py27-pyramid14
        - python: 2.7
          env: TOXENV=py27-pyramid15
        - python: 3.5
          env: TOXENV=py35-pyramid16
        - python: 3.5
          env: TOXENV=py35-pyramid17

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"

