language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=py32 # no u"" support
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py2-docs
    - TOXENV=py3-docs
    - TOXENV=py2-cover,py3-cover,coverage
    - TOXENV=py27-pyramid12
    - TOXENV=py27-pyramid13
    - TOXENV=py27-pyramid14
    - TOXENV=py27-pyramid15
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
