language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py32 # no u"" support
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=cover
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
